### ISSUE TITLE
No way to use format() without stop()?

### ISSUE THREAD

**Issue by thely** [eyas-ranjous/timer-node#12]
I'd like to use this module to get regular reports of elapsed time between a central server and 6-10 users for sessions that I expect to be ~10 minutes or so. If possible, I'd like to just keep the timer running for the duration of that session. But it seems like I can't get any output out of `format()` (or `timer.seconds()`, or `timer.milliseconds()`), unless I do `timer.stop().format()`. I noticed this is how the functions are declared in the tests, as well - you can only get information after the timer stops. Is there a way to get the elapsed duration without stopping the timer?

Related, is there a way to resume a stopped timer?

**Comment by eyas-ranjous** [comment]
Hi @thely 

Thanks for your feedback. It was not built with this use case on my mind, but nice suggestion, I can add this feature for sure.

**Comment by eyas-ranjous** [comment]
Hi @thely

A new major version **v4.0.0** has been released from timer-node. you can now log the elapsed time at any moment without stopping the timer, as well as using `.pause()` & `.resume()` on it.

```js
const { Timer } = require('timer-node');

const testTimer = new Timer('test');

testTimer.start();

console.log(testTimer.time()); // { s: 3, ms: 745, us: 248, ns: 60 }
console.log(testTimer.time()); // { s: 7, ms: 493, us: 617, ns: 811 }

testTimer.pause();

console.log(testTimer.time()); // { s: 16, ms: 204, us: 757, ns: 344 }
console.log(testTimer.time()); // { s: 16, ms: 204, us: 757, ns: 344 }

testTimer.resume();

console.log(testTimer.time()); // { s: 20, ms: 195, us: 90, ns: 52 }
console.log(testTimer.time()); // { s: 26, ms: 499, us: 200, ns: 242 }

testTimer.stop();

console.log(testTimer.time()); // { s: 39, ms: 692, us: 530, ns: 502 }
console.log(testTimer.time()); // { s: 39, ms: 692, us: 530, ns: 502 }
```
