### ISSUE TITLE
Add Typescript Type defination or directly write package in typescript

### ISSUE THREAD

**Issue by atharva-bhange** [eyas-ranjous/timer-node#14]
This is a great module but it has no type definition for typescript projects neither inbuilt types. It would be great if that was added. Thank You!

**Comment by eyas-ranjous** [comment]
Hi @atharva-bhange thanks for your feedback, nice suggestion, I added the ts definitions to the project, feel free to take a look and let me know if it looks good https://github.com/eyas-ranjous/timer-node/pull/15

**Comment by atharva-bhange** [comment]
Thanks A Lot!! i am not very well versed with writing type definition for libraries but cloned your development branch in a typescript project and was able to import the Timer class without any problem.

![image](https://user-images.githubusercontent.com/37930618/111024127-eca57700-8402-11eb-9287-47c367a08cf9.png)

I was able to import Timer but not time as your documentation for Ts says don't know if it is problem in my way of doing it or something else. 
Anyways i am going to use this on  server side and not in react app. This will be so helpful than using setInterval in js and stuff. 
Thanks Again!

**Comment by eyas-ranjous** [comment]
Ah I see. Yes it won't work in the browser unfortunately. This is a server side npm as it uses node global object "process". https://nodejs.org/api/process.html. however I will leave the definitions I added because it allows using types in backend typescript code (already tested that).

**Comment by atharva-bhange** [comment]
Yeah i also needed it in backend but didn't have a project where i could quickly test it. Np it works for me. Publish it then we all can use the new type definition!

**Comment by eyas-ranjous** [comment]
https://github.com/eyas-ranjous/timer-node/releases/tag/v4.1.0
