### ISSUE TITLE
How to tell when the timer is done?

### ISSUE THREAD

**Issue by humanfriend22** [eyas-ranjous/timer-node#24]
Sorry but I don't think I understood the Usage Instructions but how can I "know" when a timer is done? For example if the timer is done it could launch a function.

I like the flexibility of this package but I really need help with this.

Thank You in Advance.

**Comment by eyas-ranjous** [comment]
Hi! a timer is done when you explicitly call `.stop()` which concludes the running time of it. You can check if a timer has been stopped by calling `.isStopped()`.  This is not count-down library and it does not emit any events, its purpose is to measure the elapsed time manually for running tasks. If you need something to notify you when a timer is done after x seconds for example, you should use the usual `setTimeout(callback, durationInMs)`
