### ISSUE TITLE
Timer created from state (.deserialized()) does not take into account whether it is pause or not

### ISSUE THREAD

**Issue by Nakerdev** [eyas-ranjous/timer-node#26]
First at all, thank you for the open source lib. It is very usefull.

I found a bug, when you create a timer from state. It does not take into account whether it is pause or not. I made a red test where you can follow the error.

```
it('creates a timer from a serialized timer keeping paused state', async () => {
  const newTimer = new Timer(({ label: 'paused-timer-test' }));
  newTimer.start();
  await sleep(100);
  newTimer.pause();

  const timerFromState = Timer.deserialize(newTimer.serialize()); 

  expect(timerFromState.serialize()).to.deep.equal(newTimer.serialize());
});
  
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

I tried to create a pull request with the fix but i do not be able to solve the problem without break the `records ellapsed time from a past timestamp` test.

Best regards!

**Comment by eyas-ranjous** [comment]
@Nakerdev sorry for the late reply and thanks for submitting the pr. Releasing the fix soon
