### ISSUE TITLE
Feature request: Make methods chainable

### ISSUE THREAD

**Issue by stephen-last** [eyas-ranjous/timer-node#8]
Could you `return this` from `stop()` and `clear()`..?

This would enable `timer.stop().format()` and `timer.clear().start()`.

**Comment by eyas-ranjous** [comment]
sorry for the late reply, absolutely, will make the change.

**Comment by eyas-ranjous** [comment]
let me know if this PR https://github.com/node-work/timer-node/pull/9 looks good @stephen-last

**Comment by stephen-last** [comment]
Thanks @eyas-ranjous, that looks good to me...

**Comment by eyas-ranjous** [comment]
v3 published to npm
